qzone_fetch_days: 30
qzone_headers:
  Dnt: '1'
  Priority: u=1, i
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
  accept: '*/*'
  accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7
  authority: user.qzone.qq.com
  cookie: ptcz=dc033c4edfa213dfa52bfe5241945f87242e2345f828ee160bf562711ef1ac18; pgv_pvid=149336850;
    qq_domain_video_guid_verify=216279267643c94b; _qimei_uuid42=1810309271d10088a6e3f71254796e2480069178d7;
    _qimei_q36=; _qimei_h38=2db80559a6e3f71254796e2402000002718103; eas_sid=n1a760t743V894x0P460b962P2;
    RK=6StkxdlHWz; pac_uid=0_a90341a78e064; iip=0; QZ_FE_WEBP_SUPPORT=1; fopenid=F2F2BFC6FD2AE086252622D5C8D46E95;
    token=CB66933E1484B647172FCF9492F89202; it_c=0; _qimei_fingerprint=6a7616775ae3e4103d169a092213c08b;
    suid=user_0_a90341a78e064; qz_screen=1920x1080; __Q_w_s__QZN_TodoMsgCnt=1; __Q_w_s_hat_seed=1;
    cpu_performance_v8=25; uin=o0437460307; skey=@mjzF1NZTk; p_uin=o0437460307; pt4_token=hXNY2jct1S0YHqhnp3TrZ5ah5k9CcTMYEf98ILZgvRc_;
    p_skey=Gsv20lA4ifkoZLXSm*H6CCPhki3MTvqIRg4Usoaow-w_; Loading=Yes; qzmusicplayer=qzone_player_437460307_1729570751466;
    qqmusic_uin=0437460307; qqmusic_key=@mjzF1NZTk; qqmusic_fromtag=6; pgv_info=ssid=s2839198557;
    randomSeed=182469; rv2=80EFE595CB5C30EC5DD81947FFDBD4BE18927A264286A23DD3; property20=1996E37D37A2AF011C754B14EAED9AB6EB5BA7D2A0828CE22E8F894CD9C12D0C0353A836DA2B0C51
  sec-ch-ua: '"Microsoft Edge";v="125", "Chromium";v="125", "Not.A/Brand";v="24"'
  sec-ch-ua-mobile: ?0
  sec-fetch-dest: empty
  sec-fetch-mode: cors
  sec-fetch-site: same-origin
qzone_pages: 1
root_directory: F:/owl/root
weibo_fetch_days: 2
weibo_headers:
  Accept: application/json, text/plain, */*
  Accept-Encoding: gzip, deflate, br, zstd
  Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7
  Client-Version: v2.45.38
  Cookie: UOR=,,cn.bing.com; SINAGLOBAL=3234014125719.2446.1716885728380; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WFpIlcOwdGQ-iXMICYuovHv5JpX5KMhUgL.Fo-cSozc1hBfeKB2dJLoI0qLxKMLBKqL1h2LxKqLB-BLBKzLxKnL1hqL1-eLxKqL1hnL1K2LxK-LBKBLBoBLxK-L1heL12qt;
    ULV=1727073808165:7:1:1:8426195069738.507.1727073808159:1720504108173; XSRF-TOKEN=ToHm7d7D_pgXh81JRESnHAi6;
    ALF=1731651283; SUB=_2A25KCymCDeRhGeNI7VAX-CrJyjiIHXVpaSNKrDV8PUJbkNAbLRnskW1NSF2BWE_vpoYKEK-FvRpLENigg9t4CZ0t;
    WBPSESS=sEv4Cq28yjXYeVvKaLIIIL8kzkNE9RjzvYXXKe-MHtxmXZCyiFYZ25eabg7p2ulCutWpZ3lt_nEMZgaNu68b0GA1Htv2upMAUD_UtsWq8pFDaZhDdHHG_slUo9Ysv3DRyldag6IUnrp8xgGXJfd79g==
  Dnt: '1'
  Priority: u=1, i
  Sec-Ch-Ua: '"Microsoft Edge";v="125", "Chromium";v="125", "Not.A/Brand";v="24"'
  Sec-Ch-Ua-Mobile: ?0
  Sec-Ch-Ua-Platform: '"Windows"'
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  Sec-Fetch-Site: same-origin
  Server-Version: v2024.06.05.2
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
  X-Requested-With: XMLHttpRequest
  X-Xsrf-Token: tMd3QBGKsmXjM94AtxgtFatg
  authority: weibo.com
  method: GET
  scheme: https
weibo_pages: 1
