qzone_fetch_days: 30
qzone_headers:
  Dnt: '1'
  Priority: u=1, i
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
  accept: '*/*'
  accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7
  authority: user.qzone.qq.com
  cookie: ptcz=dc033c4edfa213dfa52bfe5241945f87242e2345f828ee160bf562711ef1ac18; pgv_pvid=149336850;
    qq_domain_video_guid_verify=216279267643c94b; _qimei_uuid42=1810309271d10088a6e3f71254796e2480069178d7;
    _qimei_q36=; _qimei_h38=2db80559a6e3f71254796e2402000002718103; eas_sid=n1a760t743V894x0P460b962P2;
    RK=6StkxdlHWz; pac_uid=0_a90341a78e064; iip=0; QZ_FE_WEBP_SUPPORT=1; fopenid=F2F2BFC6FD2AE086252622D5C8D46E95;
    token=CB66933E1484B647172FCF9492F89202; it_c=0; _qimei_fingerprint=6a7616775ae3e4103d169a092213c08b;
    suid=user_0_a90341a78e064; qz_screen=1920x1080; __Q_w_s__QZN_TodoMsgCnt=1; __Q_w_s_hat_seed=1;
    uin=o0437460307; p_uin=o0437460307; qqmusic_uin=0437460307; qqmusic_fromtag=6;
    pgv_info=ssid=s2839198557; randomSeed=182469; cpu_performance_v8=43; skey=@7foSYqEpU;
    pt4_token=DLqyKYZ9EysfzIys9wUcVg0W-NgrwGfsL5uKYOv4lsI_; p_skey=8v-CtBwqCKEbr0jtbI6R6kqFgGWVjQCIUXuSv*AaNiU_;
    Loading=Yes; qzmusicplayer=qzone_player_437460307_1729659097897; qqmusic_key=@7foSYqEpU;
    rv2=80EA9831E5CF05933C6D201A64F8FE11F44E7ABA3D80D1FB46; property20=15846882B85B0ABBB6989C1BD766679B84871D2EB0778AF34510025F4E0A3CFF771F81FACEB95A32
  sec-ch-ua: '"Microsoft Edge";v="125", "Chromium";v="125", "Not.A/Brand";v="24"'
  sec-ch-ua-mobile: ?0
  sec-fetch-dest: empty
  sec-fetch-mode: cors
  sec-fetch-site: same-origin
qzone_pages: 1
root_directory: F:/owl/root
weibo_fetch_days: 2
weibo_headers:
  Accept: application/json, text/plain, */*
  Accept-Encoding: gzip, deflate, br, zstd
  Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7
  Client-Version: v2.45.38
  Cookie: UOR=,,cn.bing.com; SINAGLOBAL=3234014125719.2446.1716885728380; SUBP=0033WrSXqPxfM725Ws9jqgMF55529P9D9WFpIlcOwdGQ-iXMICYuovHv5JpX5KMhUgL.Fo-cSozc1hBfeKB2dJLoI0qLxKMLBKqL1h2LxKqLB-BLBKzLxKnL1hqL1-eLxKqL1hnL1K2LxK-LBKBLBoBLxK-L1heL12qt;
    ULV=1729236722456:8:1:1:3358406003431.9507.1729236722352:1727073808165; XSRF-TOKEN=OdToyvJwdxXyC2VU7e70tUHt;
    ALF=1732256182; SUB=_2A25KHOTlDeRhGeNI7VAX-CrJyjiIHXVpUHgtrDV8PUJbkNAbLUHhkW1NSF2BWJ0syLA4Shx66NSOlX6cAmit2qQb;
    WBPSESS=sEv4Cq28yjXYeVvKaLIIIL8kzkNE9RjzvYXXKe-MHtxmXZCyiFYZ25eabg7p2ulCutWpZ3lt_nEMZgaNu68b0Ifrzo5Z-EB0Xmtj2A8Cy6Zl6NH88Nr_ShILF2e3ooimjDBQ_EWFb-ZbrQjxFFfgpw==
  Dnt: '1'
  Priority: u=1, i
  Sec-Ch-Ua: '"Microsoft Edge";v="125", "Chromium";v="125", "Not.A/Brand";v="24"'
  Sec-Ch-Ua-Mobile: ?0
  Sec-Ch-Ua-Platform: '"Windows"'
  Sec-Fetch-Dest: empty
  Sec-Fetch-Mode: cors
  Sec-Fetch-Site: same-origin
  Server-Version: v2024.06.05.2
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
    like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
  X-Requested-With: XMLHttpRequest
  X-Xsrf-Token: tMd3QBGKsmXjM94AtxgtFatg
  authority: weibo.com
  method: GET
  scheme: https
weibo_pages: 1
